### ISSUE TITLE
Publish this package to PyPI & install it from there

### ISSUE THREAD

**Issue by kdmccormick** [openedx/MongoDBProxy#18]
## Background

Part of [this epic](https://github.com/openedx/wg-developer-experience/issues/153).

This package is currently installed into edx-platform [directly from GitHub](https://github.com/openedx/edx-platform/tree/master/requirements/edx/github.in). This is non-ideal because:
* GitHub-hosted requirements take significantly longer (> 4x) to install than PyPI-hosted requirements
* GitHub-hosted requirement pins cannot be upgraded using our standard `make upgrade` workflow.

## Request

* Audit this package's `setup.py` to make sure it looks right before publishing. You can test it out by:
  * creating a virtual environment
  * installing package requirements 
  * running `python setup.py sdist bdist_wheel`
  * checking the contents of the generated `dist/` folder. The folder should contain a .tar.gz that can be unpacked, yielding the contents of what would be pushed to PyPI. The unpacked .tar.gz should include all Python source files (other than test files) as well as a LICENSE and any assets/resources needed for the block to work.
  * rename it to an available project name, like openedx-mongodbproxy
* Publish this package to PyPI whenever a release happens. Open edX provides a workflow template for this: https://github.com/openedx/mongodbproxy/actions/new?category=owner 
* Create a release in order to trigger an initial publish to PyPI
* In edx-platform, remove the mongodbproxy GitHub pin from [github.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/github.in), and add openedx-mongodbproxy to [base.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/base.in), which holds all PyPI-hosted base dependencies. Run `make upgrade` so that the change is reflected in the requirements `*.txt` files.

**Comment by kdmccormick** [comment]
FYI @UsamaSadiq

**Comment by UsamaSadiq** [comment]
- [ ] Followed the instructions mentioned in the description to test the package build files locally. 
- [ ] Tested the package upload & installation on TestPyPI instance successfully.
- [ ] Removed the package distribution & project file from TestPyPI after successfully testing the installation.

**Comment by UsamaSadiq** [comment]
PR to add pypi-publish workflow in the repo: https://github.com/openedx/MongoDBProxy/pull/19

**Comment by UsamaSadiq** [comment]
- [ ] `pypi-publish` workflow added in the repo. 
- [ ] Successfully released PyPI version https://pypi.org/project/openedx-mongodbproxy/

**Comment by UsamaSadiq** [comment]
- [ ] Created Sandbox instance https://mongodbproxy.sandbox.edx.org/dashboard to test this change.

**Comment by UsamaSadiq** [comment]
- [x] Migrated edx-platform to use `PyPI package` in the PR https://github.com/openedx/edx-platform/pull/32259.
